name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build and Push to Docker Hub
      uses: azure/docker-login@v1
      with:            
        username: milonamir
        password: c98cb1ee-6b4b-448e-ad70-007484e96353
        
    - name: Build and Push container to registry
      run: |        
        docker push milonamir/milo-example5555:v1.0.1
        

